### ISSUE TITLE
APP window size

### ISSUE THREAD

**Issue by dagneycooke** [OpenTrons/opentrons-api#103]
The app reacts weirdly to trying to adjust the window size.  Also, if it loads and thinks it is a hood robot, the window is smaller, and doesn't readjust when you connect to an OT-One PRO (maybe it should default to a larger size in case it is a PRO?
![screen shot 2016-11-14 at 9 46 54 am](https://cloud.githubusercontent.com/assets/14912982/20268981/4ce8d608-aa4f-11e6-8017-b8afaea4e7d0.png)

**Comment by andySigler** [comment]
app issue, fixed
