### ISSUE TITLE
pulling wrong pipette name into app

### ISSUE THREAD

**Issue by dagneycooke** [OpenTrons/opentrons-api#108]
both p200s are being called p10 in the description 
![screen shot 2016-11-14 at 10 11 47 am](https://cloud.githubusercontent.com/assets/14912982/20269845/dd0ed0ae-aa52-11e6-8ba0-294d2fe831f0.png)
![screen shot 2016-11-14 at 10 11 54 am](https://cloud.githubusercontent.com/assets/14912982/20269844/dd0ee9a4-aa52-11e6-8222-8a1b28af65a9.png)
![screen shot 2016-11-14 at 10 12 00 am](https://cloud.githubusercontent.com/assets/14912982/20269846/dd0fcfea-aa52-11e6-9ef1-37b0f6f87bfb.png)

**Comment by andySigler** [comment]
app issue, and fixed
