### ISSUE TITLE
Move to action is incorrect

### ISSUE THREAD

**Issue by dagneycooke** [OpenTrons/opentrons-api#191]
When calibrating a container and selecting "move to container", the robot moves the z axis DOWN first, and then moves XY.  This does not take into account other containers on the deck.  All move to buttons should move UP the Z axis first, then make XY movements.

**Comment by astaff** [comment]
Reference: https://github.com/OpenTrons/opentrons-app/issues/98

**Comment by andySigler** [comment]
https://github.com/OpenTrons/opentrons-api/pull/194
