### ISSUE TITLE
Z height bug

### ISSUE THREAD

**Issue by willcanine** [OpenTrons/opentrons-api#57]
calibrating the XYZ of tiprack using old app, pipette goes to correct XY, but not far enough down the Z

**Comment by astaff** [comment]
Make sure if you are calibrating for top in 1.2 you are calling `import_calibration_json` with `calibrated_top=True`. Or if you are calibrating for the bottom in 1.2 you are calling `import_calibration_json` with `calibrated_top=False` (default)? Also if you are calibrating for the top, make sure the container height is correct.

**Comment by andySigler** [comment]
fixed
