### ISSUE TITLE
15ml / 50ml tube rack container file fix

### ISSUE THREAD

**Issue by willcanine** [OpenTrons/opentrons-api#58]
from OT user Magnus: 'I think there is a bug in the containers file for the tube-rack-15_50mL for positions C1 and C2. The x position should be 64, not 54. (Compare to the 32 of the B1 and B2)'

**Comment by astaff** [comment]
@andySigler

**Comment by andySigler** [comment]
fixed here:

https://github.com/OpenTrons/opentrons-api/commit/e2dca6d7d06808298de27ac0222640d6764b3228
